/**
 * PixelBoop Session Types
 * TypeScript interfaces for PixelBoop jam session management
 * Adapted from Centaurus session types for PixelBoop use case
 */

/**
 * Participant in a PixelBoop jam session
 * Tracked via Supabase Realtime Presence API
 */
export interface PixelBoopParticipant {
  /** Unique presence ID (auto-generated by Supabase) */
  id: string;

  /** User display name */
  name: string;

  /** Whether this user created the session */
  isHost: boolean;

  /** Device type (ios, web, android) */
  deviceType: 'ios' | 'web' | 'android';

  /** ISO timestamp when user joined */
  joinedAt: string;
}

/**
 * Pattern edit delta for efficient state sync
 * Only transmits changed notes, not entire pattern
 */
export interface PatternEditDelta {
  /** Track index (0-7) */
  track: number;

  /** Step index (0-15) */
  step: number;

  /** MIDI note number (null = clear step) */
  note: number | null;

  /** Velocity (0-127, 0 = note off) */
  velocity: number;

  /** Note duration (0.0-1.0, fraction of step) */
  duration: number;

  /** Timestamp for conflict resolution */
  timestamp: number;
}

/**
 * Playback state sync
 */
export interface PlaybackState {
  /** Transport playing/stopped */
  isPlaying: boolean;

  /** Current step position (0-15) */
  currentStep: number;
}

/**
 * Track state sync (mute/solo)
 */
export interface TrackState {
  /** Track index (0-7) */
  track: number;

  /** Track muted */
  muted: boolean;

  /** Track soloed */
  solo: boolean;
}

/**
 * Tempo change event
 */
export interface TempoChange {
  /** BPM (40-300) */
  bpm: number;
}

/**
 * Connection status for session service
 */
export type PixelBoopConnectionStatus = 'connected' | 'connecting' | 'disconnected';

/**
 * Broadcast event types for PixelBoop
 */
export type PixelBoopBroadcastEventType =
  | 'pattern-edit'
  | 'playback-state'
  | 'tempo-change'
  | 'track-state';

/**
 * Broadcast payload structure
 */
export interface PixelBoopBroadcastPayload {
  /** Pattern edit event */
  patternEdit?: PatternEditDelta;

  /** Playback state event */
  playbackState?: PlaybackState;

  /** Tempo change event */
  tempoChange?: TempoChange;

  /** Track state event */
  trackState?: TrackState;
}
