/**
 * Session Types
 * TypeScript interfaces for jam session management
 * Story 7.2 - Supabase Realtime Service Layer
 */

/**
 * Participant in a jam session
 * Tracked via Supabase Realtime Presence API
 */
export interface Participant {
  /** Unique presence ID (auto-generated by Supabase) */
  id: string;

  /** User display name */
  name: string;

  /** Whether this user created the session */
  isHost: boolean;

  /** ISO timestamp when user joined */
  joinedAt: string;
}

/**
 * Session state synchronized across all participants
 * Transmitted via Supabase Realtime Broadcast API
 */
export interface SessionState {
  /** Tempo in BPM (40-300) */
  tempo: number;

  /** Global transport state */
  isPlaying: boolean;

  /** Musical key (optional, synced separately in Story 7.7) */
  key?: string;

  /** Scale pattern (optional, synced separately in Story 7.7) */
  scale?: string;
}

/**
 * Connection status for session service
 */
export type ConnectionStatus = 'connected' | 'connecting' | 'disconnected';

/**
 * Presence sync payload
 * Raw Supabase Presence state
 */
export interface PresenceState {
  [key: string]: {
    name: string;
    isHost: boolean;
    joinedAt: string;
  }[];
}

/**
 * Broadcast event types
 */
export type BroadcastEventType =
  | 'tempo-change'
  | 'playback-control'
  | 'key-change'
  | 'state-request'
  | 'state-response'
  | 'drum-step'
  | 'color-mode';

/**
 * Drum step event data (Story 17.1)
 * Delta-based state sync for drum pattern editing
 */
export interface DrumStepEvent {
  /** Track index (0-7) */
  track: number;

  /** Step index (0-15) */
  step: number;

  /** Step enabled/disabled */
  enabled: boolean;

  /** Step velocity (0-100) */
  velocity: number;
}

/**
 * Broadcast payload structure
 */
export interface BroadcastPayload {
  /** Tempo change event */
  tempo?: number;

  /** Playback control event */
  isPlaying?: boolean;

  /** Key/scale change event */
  key?: string;
  scale?: string;

  /** State request/response (Story 7.7) */
  requesterId?: string;
  sessionState?: SessionState;

  /** Drum step change event (Story 17.1) */
  drumStep?: DrumStepEvent;

  /** Color mode change event (Story 17.2) */
  mode?: string; // 'chromatic' | 'harmonic' | 'spectrum'
}
